@extends('layouts.admin')

@section('title', 'Mindora || Admin Dashboard')

@section('content')

<!-- =========================
 PAGE TITLE + BREADCRUMB
========================== -->
<div class="pagetitle">
    <h1>Dashboard</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('admin.dashboard') }}">Home</a>
            </li>
            <li class="breadcrumb-item active">Dashboard</li>
        </ol>
    </nav>
</div>

<section class="section dashboard">

    <!-- =========================
        TOP OVERVIEW STATS
    ========================== -->
    <div class="row">

        <!-- TOTAL QUESTIONS -->
        <div class="col-xl-3 col-md-6">
            <div class="card info-card">
                <div class="card-body">
                    <h5 class="card-title">Questions</h5>
                    <div class="d-flex align-items-center">
                        <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                            <i class="bi bi-question-circle"></i>
                        </div>
                        <div class="ps-3">
                            <h6>{{ $stats['questions'] ?? 0 }}</h6>
                            <span class="text-muted small">Total in system</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- SCRAPED -->
        <div class="col-xl-3 col-md-6">
            <div class="card info-card">
                <div class="card-body">
                    <h5 class="card-title">Scraped</h5>
                    <div class="d-flex align-items-center">
                        <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                            <i class="bi bi-globe"></i>
                        </div>
                        <div class="ps-3">
                            <h6>{{ $stats['scraped'] ?? 0 }}</h6>
                            <span class="text-muted small">Pending review</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- AI DRAFTS -->
        <div class="col-xl-3 col-md-6">
            <div class="card info-card">
                <div class="card-body">
                    <h5 class="card-title">AI Drafts</h5>
                    <div class="d-flex align-items-center">
                        <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                            <i class="bi bi-robot"></i>
                        </div>
                        <div class="ps-3">
                            <h6>{{ $stats['ai_drafts'] ?? 0 }}</h6>
                            <span class="text-muted small">Generated by AI</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- PUBLISHED -->
        <div class="col-xl-3 col-md-6">
            <div class="card info-card">
                <div class="card-body">
                    <h5 class="card-title">Published</h5>
                    <div class="d-flex align-items-center">
                        <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                            <i class="bi bi-check-circle"></i>
                        </div>
                        <div class="ps-3">
                            <h6>{{ $stats['published'] ?? 0 }}</h6>
                            <span class="text-muted small">Live pages</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- =========================
        QUICK ACCESS MODULES
    ========================== -->
    <div class="row mt-4">

        <!-- QUESTIONS -->
        <div class="col-lg-4">
            <div class="card text-center h-100">
                <div class="card-body">
                    <i class="bi bi-question-square fs-1 text-primary"></i>
                    <h5 class="mt-3">Question Management</h5>
                    <p class="text-muted">
                        Create, edit, review & publish questions
                    </p>
                    <a href="{{ route('admin.questions.index') }}"
                       class="btn btn-sm btn-primary">
                        Open Module
                    </a>
                </div>
            </div>
        </div>

        <!-- SCRAPING (PHASE 4) -->
        <div class="col-lg-4">
            <div class="card text-center h-100">
                <div class="card-body">
                    <i class="bi bi-globe2 fs-1 text-success"></i>
                    <h5 class="mt-3">Scraping System</h5>
                    <p class="text-muted">
                        Manage sources & scraped drafts
                    </p>
                    <span class="badge bg-secondary">Phase 4</span>
                </div>
            </div>
        </div>

        <!-- AI CONTENT (PHASE 5) -->
        <div class="col-lg-4">
            <div class="card text-center h-100">
                <div class="card-body">
                    <i class="bi bi-cpu fs-1 text-warning"></i>
                    <h5 class="mt-3">AI Content</h5>
                    <p class="text-muted">
                        AI jobs, drafts & quality control
                    </p>
                    <span class="badge bg-secondary">Phase 5</span>
                </div>
            </div>
        </div>

    </div>

    <!-- =========================
        SYSTEM HEALTH & ADMIN INFO
    ========================== -->
    <div class="row mt-4">

        <!-- SYSTEM HEALTH -->
        <div class="col-lg-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">System Health</h5>

                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between">
                            Authentication
                            <span class="badge bg-success">Active</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between">
                            Admin Role
                            <span class="badge bg-success">Enabled</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between">
                            Automation
                            <span class="badge bg-secondary">Phase 4</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between">
                            SEO Engine
                            <span class="badge bg-secondary">Phase 7</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- ADMIN INFO -->
        <div class="col-lg-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Admin Information</h5>

                    <table class="table table-sm">
                        <tr>
                            <th>Name</th>
                            <td>{{ auth()->user()->name }}</td>
                        </tr>
                        <tr>
                            <th>Email</th>
                            <td>{{ auth()->user()->email }}</td>
                        </tr>
                        <tr>
                            <th>Role</th>
                            <td>
                                <span class="badge bg-primary">Admin</span>
                            </td>
                        </tr>
                        <tr>
                            <th>Last Login</th>
                            <td>Tracking starts Phase 6</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>

    </div>

</section>
@endsection
